### PR TITLE
Added index support

### PR DESCRIPTION
**Pull request by deeptimathur1904**
## Summary
Automated and hideable index generation using Hugo shortcode.

## Issue link(s)
https://github.com/sarveshraj/me/issues/12, #34 

## Changes
 The index is hidden by default into a button on the left.
 Hovering on the button pulls the index from the left side.
 Auto-generated using the heading tags, with smooth scrolling to the correct heading.

## Checklist
- [x]  This PR represents a single feature, fix, or change
- [x]  These changes have been tested locally
- [ ]  Updated relevant documentation (feature wikis, README)
- [x]  Screenshots added for UI changes

### CODE REVIEW

**Comment by deeptimathur1904** [comment]
image

**Comment by deeptimathur1904** [comment]
https://github.com/sarveshraj/me/issues/34

**Comment by sarveshraj** [comment]
Updated the code to support #34

**Comment by sarveshraj** [comment]
Screenshot 2020-04-25 at 7 53 50 PM
Screenshot 2020-04-25 at 7 53 14 PM

**Pull request merged**
